### ISSUE TITLE
XSS vectors

### ISSUE THREAD

**Issue by TGThorax** [Mohagames205/Flowpanel#12]
Be wary of user data. A user can give the following username or reason:
```
<script>console.log("123")</script>
```
The script will then run for every user that visits the `home` page, since you echo that in the table  without checking that the input isn't malicious. This type of attack is called **XSS** or **cross-site scripting.**

The username and reason are examples of _stored_ XSS: you store the value the attacker gives you and later you distribute it to (other) users.

You also have a _reflected_ XSS in your code. That is when an attacker can create a link that might execute code. In your example: `home.php?naam=javascript_here`. If an attacker can trick a user into going to that link, they can make that user execute whatever code they want.

Restricting the length of the possible usernames or reasons is not enough to mitigate malicious attacks. 255 characters is more than enough to steal someone's cookie, and thus their login (that's why a lot of sites ask you for your password again if you want to change it, even if you just logged in with it. That way even someone who stole your cookie can't change your password unless they knew it in the first place).

The moral of the story: "**_Never_ never _never_ ever trust user input. Always assume the user is malicious.**" 

Check every echo you do of user definable things. Add `htmlspecialchars` to those to sanitize them.  Maybe penalise users that you suspect are trying to attack you. You might also want to check out CSRF and mitigations (samesite, CSRF tokens, ...) in further development.

**Comment by Mohagames205** [comment]
I think I fixed it! Thank you for letting me know!
